/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author IQBAL NOTEBOOK
 */
public class receipt extends javax.swing.JFrame {

    Connection cn = confestix.koneksi.Koneksi();
    ResultSet rs;
    Statement stm;

    /**
     * Creates new form receipt
     */
    public void DoConnectUser() {
        try {
            stm = cn.createStatement();
            String sql = "select*from user";
            rs = stm.executeQuery(sql);

            while (rs.next()) {
                int id_user = rs.getInt("id_user");
                String name = rs.getString("name");
                String id = Integer.toString(id_user);
                tf_name.setText(name);
                tf_id.setText(id);
            }
        } catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }

    public void ConnectTicket() {
        try {
            stm = cn.createStatement();
            String sql = "select*from ticketdetail";
            rs = stm.executeQuery(sql);

            while (rs.next()) {
                int total_price = rs.getInt("total_price");
                int amount_ticket = rs.getInt("ticket_amount");
                String price = Integer.toString(total_price);
                String amount = Integer.toString(amount_ticket);
                tf_total.setText(amount);
                tf_price.setText(price);

            }
        } catch (SQLException err) {
            System.out.println(err.getMessage());
        }

    }

    public void ConnectEvent() {
        try {
            stm = cn.createStatement();
            String sql = "select*from event";
            rs = stm.executeQuery(sql);

            while (rs.next()) {
                String event = rs.getString("event_name");
                tf_event.setText(event);
            }
        } catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }

    public receipt() {
        initComponents();
        DoConnectUser();
        ConnectTicket();
        ConnectEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf_id = new javax.swing.JLabel();
        tf_name = new javax.swing.JLabel();
        tf_event = new javax.swing.JLabel();
        tf_total = new javax.swing.JLabel();
        tf_price = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your ID :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 90, 50, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Event Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 150, 75, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Ticket :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 180, 74, 15);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("=================================================");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 210, 400, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total price :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 230, 66, 15);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 280, 83, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 120, 39, 15);

        tf_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_id.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tf_id);
        tf_id.setBounds(160, 90, 146, 21);

        tf_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tf_name);
        tf_name.setBounds(160, 120, 146, 18);

        tf_event.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_event.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tf_event);
        tf_event.setBounds(160, 150, 146, 21);

        tf_total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_total.setForeground(new java.awt.Color(255, 255, 255));
        tf_total.setPreferredSize(new java.awt.Dimension(34, 21));
        getContentPane().add(tf_total);
        tf_total.setBounds(160, 180, 146, 21);

        tf_price.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_price.setForeground(new java.awt.Color(255, 255, 255));
        tf_price.setMaximumSize(new java.awt.Dimension(34, 21));
        getContentPane().add(tf_price);
        tf_price.setBounds(160, 230, 146, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mutiara\\Downloads\\confestix\\9.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 318);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel tf_event;
    private javax.swing.JLabel tf_id;
    private javax.swing.JLabel tf_name;
    private javax.swing.JLabel tf_price;
    private javax.swing.JLabel tf_total;
    // End of variables declaration//GEN-END:variables
}
